"""Browser interaction checks. Requires Python Playwright and Chromium.
By default serves the project at http://127.0.0.1:8765. --memory runs the
self-contained HTML in an opaque about:blank context with a storage test double
(used in environments whose browser policy blocks navigation).
"""
import argparse
import json
from pathlib import Path
from playwright.sync_api import sync_playwright
parser=argparse.ArgumentParser()
parser.add_argument('--memory',action='store_true')
parser.add_argument('--executable',default='/usr/bin/chromium')
parser.add_argument('--url',default='http://127.0.0.1:8765/')
args=parser.parse_args()
ROOT=Path(__file__).resolve().parents[1]
results=[]
def check(name, condition):
    assert condition, name
    results.append({'test':name,'passed':True})
with sync_playwright() as pw:
    browser=pw.chromium.launch(executable_path=args.executable,headless=True,args=['--no-sandbox','--enable-unsafe-webgpu','--use-angle=swiftshader'])
    page=browser.new_page(viewport={'width':1600,'height':1000},device_scale_factor=1,accept_downloads=True)
    errors=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    def load_page(target):
        if args.memory:
            target.evaluate('''()=>{const data=new Map();Object.defineProperty(window,'localStorage',{configurable:true,value:{getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,String(v)),removeItem:k=>data.delete(k)}});}''')
            target.set_content((ROOT/'Draftline.html').read_text(),wait_until='load')
        else:
            target.goto(args.url,wait_until='networkidle')
        target.wait_for_timeout(1200)
    load_page(page)
    check('Initial sample renders 308 entities',page.evaluate('draftline.renderer.records.length')==308)
    check('Render backend is reported truthfully',page.evaluate('document.querySelector("#engineLabel").textContent===draftline.renderer.mode'))
    check('No initial JavaScript errors',not errors)
    if not args.memory:
        page.reload(wait_until='networkidle')
        check('Persistent drawing recovers across reload',page.evaluate('draftline.model.entities.size')==308)
    def js(s): return page.evaluate(s)
    js("draftline.execute('LINE 0,0 2000,0');draftline.execute('')")
    check('Exact command-line LINE insertion',js('draftline.model.entities.size')==309)
    check('Exact model coordinates',js('(()=>{const e=[...draftline.model.entities.values()].at(-1);return e.type==="LINE"&&e.a.x===0&&e.b.x===2000&&e.b.y===0})()'))
    js("draftline.action('undo')")
    check('Undo removes line',js('draftline.model.entities.size')==308)
    js("draftline.action('redo')")
    check('Redo restores line',js('draftline.model.entities.size')==309)
    js("draftline.execute('CIRCLE');draftline.execute('1000,1000');draftline.execute('250')")
    check('Numeric circle radius',js('[...draftline.model.entities.values()].at(-1).radius')==250)
    circle_id=js('[...draftline.model.entities.values()].at(-1).id')
    page.evaluate("id=>{draftline.select([id]);draftline.execute('MOVE');draftline.execute('0,0');draftline.execute('@500,200')}",circle_id)
    check('Move uses relative displacement',js(f'draftline.model.entities.get({json.dumps(circle_id)}).center.x')==1500)
    page.evaluate("id=>{draftline.select([id]);draftline.execute('COPY');draftline.execute('0,0');draftline.execute('@1000,0')}",circle_id)
    check('Copy creates independent geometry',js('draftline.model.entities.size')==311)
    page.evaluate("id=>{draftline.select([id]);draftline.execute('SCALE');draftline.execute('1500,1200');draftline.execute('2')}",circle_id)
    check('Scale preserves center and doubles radius',js(f'draftline.model.entities.get({json.dumps(circle_id)}).radius')==500)
    js("draftline.execute('RECTANGLE');draftline.execute('20000,20000');draftline.execute('22000,22000')")
    rectangle_id=js('[...draftline.model.entities.values()].at(-1).id')
    check('Rectangle is a closed polyline',js('[...draftline.model.entities.values()].at(-1).closed'))
    page.evaluate("id=>{draftline.select([id]);draftline.execute('HATCH')}",rectangle_id)
    check('Hatch uses selected closed boundary',js('[...draftline.model.entities.values()].at(-1).type')=='HATCH')
    page.evaluate("id=>{draftline.select([id]);draftline.execute('EXPLODE')}",rectangle_id)
    check('Explode removes source polyline',not js(f'draftline.model.entities.has({json.dumps(rectangle_id)})'))
    check('Explode creates four lines',js('[...draftline.state.selection].every(id=>draftline.model.entities.get(id).type==="LINE")'))
    js("draftline.execute('PLINE');draftline.execute('30000,30000');draftline.execute('@100,0');draftline.execute('@0,100');draftline.execute('C')")
    check('Polyline closes using C',js('[...draftline.model.entities.values()].at(-1).closed'))
    js("draftline.execute('DIMALIGNED');draftline.execute('0,0');draftline.execute('1000,1000');draftline.execute('0,500')")
    check('Aligned dimension creates native entity',js('[...draftline.model.entities.values()].at(-1).orientation')=='aligned')
    js("draftline.execute('ARC');draftline.execute('1,0');draftline.execute('0,1');draftline.execute('-1,0')")
    check('3-point arc has correct radius',abs(js('[...draftline.model.entities.values()].at(-1).radius')-1)<1e-8)
    js("draftline.action('cancel');draftline.execute('TEXT');draftline.execute('100,200')")
    page.locator('#dialog-text').fill('Browser-tested annotation')
    page.locator('#dialog-height').fill('100')
    page.locator('[data-dialog-action=place]').click()
    check('Text dialog inserts editable TEXT',js('[...draftline.model.entities.values()].at(-1).text')=='Browser-tested annotation')
    page.locator('[data-action=add-layer]').first.click()
    page.locator('#dialog-name').fill('TEST-LAYER')
    page.locator('[data-dialog-action=create]').click()
    check('Layer dialog creates and activates layer',js('draftline.model.activeLayer')=='TEST-LAYER')
    before=js('draftline.renderer.showGrid')
    page.locator('#gridToggle').click()
    check('Grid toggle updates renderer',js('draftline.renderer.showGrid')!=before)
    page.locator('#orthoToggle').click()
    check('Ortho toggle updates drawing constraint',js('draftline.state.ortho'))
    page.locator('[data-tab=view]').click()
    check('View tab exposes navigation tools',page.locator('#ribbon [data-action=fit]').count()==1)
    page.locator('#ribbon [data-action=theme]').click()
    check('Dark UI theme applies',page.locator('body.dark-ui').count()==1)
    svg=js('draftline.exportSVG()')
    check('SVG export contains vector paths and text','<path ' in svg and 'Browser-tested annotation' in svg)
    exported=js('draftline.exportDXF()')
    check('DXF export is a real DXF document','AC1027' in exported and 'ENTITIES' in exported and exported.endswith('EOF\r\n'))
    imported=page.evaluate("async text=>{const doc=await draftline.importText(text,'roundtrip.dxf',false);return doc.entities.length}",exported)
    check('Browser DXF import round-trips entity count',imported==js('draftline.model.entities.size'))
    # Reset sample for pointer testing and clean screenshots.
    js("draftline.action('cancel');draftline.model.load(draftline.createDemo());draftline.renderer.rebuild();draftline.renderer.fit();draftline.renderer.invalidate();document.body.classList.remove('dark-ui')")
    page.locator('[data-tab=home]').click()
    page.wait_for_timeout(200)
    e=js('(()=>{const e=[...draftline.model.entities.values()].find(e=>e.type==="LINE"&&e.layer==="A-DOOR");return {id:e.id,p:draftline.renderer.worldToScreen({x:(e.a.x+e.b.x)/2,y:(e.a.y+e.b.y)/2})}})()')
    box=page.locator('#overlayCanvas').bounding_box()
    page.mouse.click(box['x']+e['p']['x'],box['y']+e['p']['y'])
    check('Pointer selection selects CAD geometry',js('draftline.state.selection.size')==1)
    page.keyboard.press('Escape')
    old_scale=js('draftline.renderer.camera.scale')
    page.mouse.move(box['x']+box['width']/2,box['y']+box['height']/2)
    page.mouse.wheel(0,-100)
    page.wait_for_timeout(150)
    check('Mouse-wheel zoom is anchored in drawing viewport',js('draftline.renderer.camera.scale')>old_scale)
    old_x=js('draftline.renderer.camera.x')
    page.mouse.down(button='middle')
    page.mouse.move(box['x']+box['width']/2+80,box['y']+box['height']/2,steps=6)
    page.mouse.up(button='middle')
    check('Middle-button panning updates camera',js('draftline.renderer.camera.x')!=old_x)
    js("draftline.renderer.fit();draftline.action('cancel');document.querySelector('#toastStack').replaceChildren();draftline.state.mouse=null;draftline.renderer.showGrid=true;draftline.state.ortho=false;document.querySelector('#gridToggle').classList.add('active');document.querySelector('#orthoToggle').classList.remove('active');document.querySelector('#drawingViewTitle').textContent='Ground floor plan';draftline.renderer.invalidate();draftline.action('save')")
    page.wait_for_timeout(1000)
    js("document.querySelector('#toastStack').replaceChildren()")
    page.mouse.move(1500,50)
    page.screenshot(path=str(ROOT.parent/'draftline-desktop.png'))
    js("draftline.action('theme')")
    page.screenshot(path=str(ROOT.parent/'draftline-dark.png'))
    mobile=browser.new_page(viewport={'width':390,'height':844},device_scale_factor=2,is_mobile=True,has_touch=True)
    mobile.on('pageerror',lambda e:errors.append(str(e)))
    load_page(mobile)
    check('Mobile viewport has no horizontal document overflow',mobile.evaluate('document.documentElement.scrollWidth<=innerWidth'))
    check('Mobile layout defaults to unobstructed canvas',mobile.locator('#leftPanel').is_hidden())
    mobile.locator('.rail-button[data-panel=layers]').tap()
    check('Mobile layer drawer opens',mobile.locator('#leftPanel').is_visible())
    mobile.locator('[data-action=close-left]').tap()
    mobile.evaluate("document.querySelector('#toastStack').replaceChildren();draftline.renderer.fit();draftline.renderer.invalidate()")
    mobile.wait_for_timeout(200)
    mobile.screenshot(path=str(ROOT.parent/'draftline-mobile.png'))
    check('No JavaScript exceptions across tested workflows',not errors)
    report={'backend':js('draftline.renderer.mode'),'memory_mode':args.memory,'checks':len(results),'passed':len(results),'errors':errors,'results':results}
    (ROOT/'tests/browser-results.json').write_text(json.dumps(report,indent=2))
    print(json.dumps(report,indent=2))
    browser.close()
